init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
ps: | # update and init submodules
git clone https://chromium.googlesource.com/chromium/
